{
 "title": "MsServiceMetric",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "model_name", "query": { "query": "label_values(model_name)" } },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "role", "label": "role", "query": { "query": "label_values(role)" } },
   { "name": "dp", "label": "dp", "query": { "query": "label_values(engine)" } },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "prefill_instances",
    "query": {
     "query": "label_values(vllm_profiling_batch_size_sum{role=\"prefill\"},role)"
    }
   },
   {
    "name": "decode_instances",
    "query": {
     "query": "label_values(vllm_profiling_batch_size_sum{role=\"decode\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service 总体系统指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TPS（token/s）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(model_name) (rate(vllm:iteration_tokens_total_sum{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "total_tokens"
    },
    {
     "expr": "sum by(model_name) (rate(vllm:prompt_tokens_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "prompt_tokens"
    },
    {
     "expr": "sum by(model_name) (rate(vllm:generation_tokens_total{instance=~\"$instance\", role=~\"$role\"}[$__rate_interval]))",
     "legendFormat": "generation_tokens"
    }
   ]
  },
  {
   "title": "端到端请求时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "sum(rate(vllm:e2e_request_latency_seconds_sum{instance=~\"$instance\"}[$__rate_interval])) / (sum(rate(vllm:e2e_request_latency_seconds_count{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "TTFT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{instance=~\"$instance\", instance!~\"$decode_instances\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{instance=~\"$instance\", instance!~\"$decode_instances\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{instance=~\"$instance\", instance!~\"$decode_instances\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "sum(rate(vllm:time_to_first_token_seconds_sum{instance=~\"$instance\", instance!~\"$decode_instances\"}[$__rate_interval])) / (sum(rate(vllm:time_to_first_token_seconds_count{instance=~\"$instance\", instance!~\"$decode_instances\"}[$__rate_interval])))\r\n",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "TPOT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:request_time_per_output_token_seconds_bucket{instance=~\"$instance\", instance!~\"$prefill_instances\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:request_time_per_output_token_seconds_bucket{instance=~\"$instance\", instance!~\"$prefill_instances\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:request_time_per_output_token_seconds_bucket{instance=~\"$instance\", instance!~\"$prefill_instances\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "sum(rate(vllm:request_time_per_output_token_seconds_sum{instance=~\"$instance\", instance!~\"$prefill_instances\"}[$__rate_interval])) / (sum(rate(vllm:request_time_per_output_token_seconds_count{instance=~\"$instance\", instance!~\"$prefill_instances\"}[$__rate_interval])))\r\n",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "input（输入长度）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(vllm:request_prompt_tokens_sum{instance=~\"$instance\"}[$__rate_interval])) / (sum by(instance) (rate(vllm:request_prompt_tokens_count{instance=~\"$instance\"}[$__rate_interval])))\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(vllm:request_prompt_tokens_sum{instance=~\"$instance\"}[$__rate_interval])) / (sum(rate(vllm:request_prompt_tokens_count{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "output（输出长度）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(vllm:request_generation_tokens_sum{instance=~\"$instance\"}[$__rate_interval])) / (sum by(instance) (rate(vllm:request_generation_tokens_count{instance=~\"$instance\"}[$__rate_interval])))\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(vllm:request_generation_tokens_sum{instance=~\"$instance\"}[$__rate_interval])) / (sum(rate(vllm:request_generation_tokens_count{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Second Token Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm_profiling_second_token_latency_bucket{instance=~\"$instance\", role!~\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm_profiling_second_token_latency_bucket{instance=~\"$instance\", role!~\"prefill\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm_profiling_second_token_latency_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "sum(rate(vllm_profiling_second_token_latency_sum{instance=~\"$instance\"}[$__rate_interval])) / (sum(rate(vllm_profiling_second_token_latency_count{instance=~\"$instance\", role!~\"prefill\"}[$__rate_interval])))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "完成状态",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by(finished_reason) (increase(vllm:request_success_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service 时间拆解 ${role}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "repeat": "role",
   "collapsed": true,
   "panels": [
    {
     "title": "Async CPU时间拆解",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(vllm_profiling_worker:model_runner_get_output:duration_sum{instance=~\"$instance\", role=~\"$role\"}[$__rate_interval]) / rate(vllm_profiling_worker:model_runner_get_output:duration_count{instance=~\"$instance\", role=~\"$role\"}[$__rate_interval])\r\n",
       "legendFormat": "{{instance}} overlap(AVG)"
      },
      {
       "expr": "rate(vllm_profiling_record_function_or_nullcontext_sum{instance=~\"$instance\", role=~\"$role\",name=\"prepare input\"}[$__rate_interval]) / rate(vllm_profiling_record_function_or_nullcontext_count{instance=~\"$instance\", role=~\"$role\",name=\"prepare input\"}[$__rate_interval])\r\n",
       "legendFormat": "{{instance}} prepare input(AVG)"
      },
      {
       "expr": "rate(vllm_profiling_npu:kernel_launch_sum{instance=~\"$instance\", role=~\"$role\"}[$__rate_interval]) / rate(vllm_profiling_npu:kernel_launch_count{instance=~\"$instance\", role=~\"$role\"}[$__rate_interval])\r\n",
       "legendFormat": "{{instance}} kernel_launch (AVG)"
      },
      {
       "expr": "rate(vllm_profiling_record_function_or_nullcontext_sum{instance=~\"$instance\", role=~\"$role\",name=\"Sample\"}[$__rate_interval]) / rate(vllm_profiling_record_function_or_nullcontext_count{instance=~\"$instance\", role=~\"$role\",name=\"Sample\"}[$__rate_interval])\r\n",
       "legendFormat": "{{instance}} Sample (AVG)"
      },
      {
       "expr": "rate(vllm_profiling_npu:forward_duration_sum{instance=~\"$instance\", role=~\"$role\"}[$__rate_interval]) / rate(vllm_profiling_npu:forward_duration_count{instance=~\"$instance\", role=~\"$role\"}[$__rate_interval])\r\n",
       "legendFormat": "{{instance}} forward (AVG)"
      },
      {
       "expr": "rate(vllm_profiling_record_function_or_nullcontext_sum{instance=~\"$instance\", role=~\"$role\",name=\"Draft\"}[$__rate_interval]) / rate(vllm_profiling_record_function_or_nullcontext_count{instance=~\"$instance\", role=~\"$role\",name=\"Draft\"}[$__rate_interval])\r\n",
       "legendFormat": "{{instance}} Draft (AVG)"
      },
      {
       "expr": "rate(vllm_profiling_record_function_or_nullcontext_sum{instance=~\"$instance\", role=~\"$role\",name=\"mtp_forward\"}[$__rate_interval]) / rate(vllm_profiling_record_function_or_nullcontext_count{instance=~\"$instance\", role=~\"$role\",name=\"mtp_forward\"}[$__rate_interval])\r\n",
       "legendFormat": "{{instance}} mtp forward (AVG)"
      }
     ]
    },
    {
     "title": "engine_core:process_input_queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 249 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm_profiling_engine_core:process_input_queue:duration_bucket{instance=~\"$instance\", role=~\"$role\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Prefill & Decode时长",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 257 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(vllm:request_prefill_time_seconds_sum{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(vllm:request_decode_time_seconds_sum{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "executor:prepare_inputs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 257 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm_profiling_executor:prepare_inputs:duration_bucket{instance=~\"$instance\", role=~\"$role\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "scheduler:scheduler",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 265 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm_profiling_scheduler:duration_bucket{instance=~\"$instance\", role=~\"$role\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "scheduler:update_from_output",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 265 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm_profiling_scheduler:update_from_output:duration_bucket{instance=~\"$instance\", role=~\"$role\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "executor:model_runner_execute_model",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 273 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm_profiling_executor:model_runner_execute_model:duration_bucket{instance=~\"$instance\", role=~\"$role\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Service 负载 ${role}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 314 }, "repeat": "role" },
  {
   "title": "Batch Size / DP（AVG）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 315 },
   "targets": [
    {
     "expr": "sum by (dp) (rate(vllm_profiling_batch_size_sum{instance=~\"$instance\", role=~\"$role\"}[$__rate_interval]))  /  sum by (dp) (rate(vllm_profiling_batch_size_count{instance=~\"$instance\", role=~\"$role\"}[$__rate_interval]))\r\n",
     "legendFormat": "batch size (AVG) dp {{dp}}"
    },
    {
     "expr": "sum by (dp) (rate(vllm_profiling_waiting_batch_size_sum{instance=~\"$instance\", role=~\"$role\"}[$__rate_interval]))  /  sum by (dp) (rate(vllm_profiling_waiting_batch_size_count{instance=~\"$instance\", role=~\"$role\"}[$__rate_interval]))\r\n",
     "legendFormat": "waiting size (AVG) dp {{dp}}"
    }
   ]
  },
  {
   "title": "Batch Size / DP（AVG）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 315 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, dp) (rate(vllm_profiling_batch_size_bucket{instance=~\"$instance\", role=~\"$role\"}[$__rate_interval])))",
     "legendFormat": "batch size (P99) dp {{dp}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, dp) (rate(vllm_profiling_waiting_batch_size_bucket{instance=~\"$instance\", role=~\"$role\"}[$__rate_interval])))",
     "legendFormat": "waiting size (P99) dp {{dp}}"
    }
   ]
  },
  {
   "title": "TPS / DP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 323 },
   "targets": [
    {
     "expr": "sum by(engine) (rate(vllm:iteration_tokens_total_sum{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "total_tokens: DP{{engine}"
    },
    {
     "expr": "sum by(engine) (rate(vllm:prompt_tokens_total{instance=~\"$instance\"}[$__rate_interval]))\r\n",
     "legendFormat": "prompt_tokens: DP{{engine}"
    },
    {
     "expr": "sum by(engine) (rate(vllm:generation_tokens_total{instance=~\"$instance\"}[$__rate_interval]))\r\n",
     "legendFormat": "generation_tokens: DP{{engine}"
    }
   ]
  },
  {
   "title": "Seqlen / DP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 323 },
   "targets": [
    {
     "expr": "sum by(dp) (vllm_profiling_scheduler:seqlen:sum{instance=~\"$instance\", role=~\"$role\"})",
     "legendFormat": "Sum {{ dp }}"
    },
    {
     "expr": "sum by(dp) (vllm_profiling_scheduler:seqlen:avg{instance=~\"$instance\", role=~\"$role\"})",
     "legendFormat": "Avg {{ dp }}"
    }
   ]
  },
  {
   "title": "调度器请求状态",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 331 },
   "targets": [
    {
     "expr": "vllm:num_requests_running{instance=~\"$instance\"}",
     "legendFormat": "Running {{ instance }} DP {{ engine }}"
    },
    {
     "expr": "vllm:num_requests_swapped{instance=~\"$instance\"}",
     "legendFormat": "Swapped {{ instance }} DP {{ engine }}"
    },
    {
     "expr": "vllm:num_requests_waiting{instance=~\"$instance\"}",
     "legendFormat": "Waiting {{ instance }} DP {{ engine }}"
    }
   ]
  },
  {
   "title": "队列等待时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 331 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(vllm:request_queue_time_seconds_sum{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} DP {{ engine }}"
    }
   ]
  },
  {
   "title": "投机推理平均接受率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 339 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "rate(vllm:spec_decode_num_accepted_tokens_total{instance=~\"$instance\"}[$__rate_interval]) / (rate(vllm:spec_decode_num_draft_tokens_total{instance=~\"$instance\"}[$__rate_interval]))\r\n",
     "legendFormat": "Running {{ instance }} DP {{ engine }}"
    }
   ]
  },
  {
   "title": "投机推理平均接受步长",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 339 },
   "targets": [
    {
     "expr": "rate(vllm:spec_decode_num_accepted_tokens_total{instance=~\"$instance\", role=~\"$role\"}[$__rate_interval]) / (rate(vllm:spec_decode_num_drafts_total{instance=~\"$instance\", role=~\"$role\"}[$__rate_interval]))\r\n",
     "legendFormat": "Running {{ instance }} DP {{ engine }}"
    }
   ]
  },
  {
   "title": "Service KVCache ${role}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 380 },
   "repeat": "role",
   "collapsed": true
  },
  {
   "title": "Cache利用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 381 },
   "targets": [
    {
     "expr": "vllm:kv_cache_usage_perc{instance=~\"$instance\"}\r\n",
     "legendFormat": "NPU Cache Usage dp {{dp}}"
    },
    {
     "expr": "vllm:kv_cache_usage_perc{instance=~\"$instance\",engine=~\"1\"}",
     "legendFormat": "CPU Cache Usage dp {{dp}}"
    }
   ]
  },
  {
   "title": "Prefix Cache命中率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 381 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "rate(vllm:prefix_cache_hits_total{instance=~\"$instance\"}[$__rate_interval]) / rate(vllm:prefix_cache_queries_total{instance=~\"$instance\"}[$__rate_interval])\r\n\r\n",
     "legendFormat": "NPU Cache Usage dp {{dp}}"
    }
   ]
  }
 ]
}